/**
 * Author:  Juan Pablo
 * Created: 22/03/2020
 */
-- ==============  ELIMINAR TABLAS ============== 
DROP TABLE USUARIO;
DROP TABLE CLIENTE;
DROP TABLE PERSONA;

-- ==============  CREACIÓN TABLAS ==============
CREATE TABLE PERSONA(
CEDULA VARCHAR(15) NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(30) NOT NULL,
CONTRASENIA VARCHAR(100) NOT NULL,
CORREO VARCHAR(30) NOT NULL,
TELEFONO VARCHAR(15)
);

CREATE TABLE USUARIO(
ID_PERSONA VARCHAR(15) NOT NULL,
PLACA VARCHAR(6) NOT NULL,
MARCA VARCHAR(15) NOT NULL,
ID_PROPIEDAD VARCHAR(20) NOT NULL PRIMARY KEY
);

CREATE TABLE CLIENTE(
ID INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
ID_PERSONA VARCHAR(15) NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
CUPOS INTEGER NOT NULL,
INICIO CHAR(5),
FIN CHAR(5)
);


-- ==============  ALTERAR TABLAS 'LLAVES FOREANAS'    ==============
ALTER TABLE USUARIO ADD CONSTRAINT ID_PERSONA_USUARIO FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(CEDULA);

ALTER TABLE CLIENTE ADD CONSTRAINT ID_PERSONA_CLIENTE FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA(CEDULA);